# Generated by Django 5.2.8 on 2025-11-20 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('portencia', models.IntegerField()),
                ('precio', models.FloatField()),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Auto',
        ),
    ]
