# Generated by Django 5.2.8 on 2025-11-20 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_arco_delete_auto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arco',
            old_name='portencia',
            new_name='potencia',
        ),
    ]
