# Generated by Django 5.2.8 on 2025-11-29 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_rename_portencia_arco_potencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='arco',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_arcos'),
        ),
    ]
